install:
  - ps: Install-Module -Name InvokeBuild -Force
  - ps: Install-Module -Name PSDepend -Force
  - ps: Invoke-PSDepend -Force
skip_commits:
  message: /update action.*|updated readme.*|update readme.*|update changelog.*|update docs.*|update version.*|update appveyor.*/
  files:
    - README.md
environment:
  NuGetApiKey:
    secure: wj2COfl0N8NxayKTAEVYXhTk3/XcjrB+ERJbQZquf9F/Nlwn66dOjfN6hakL9xXj
  GitHubKey:
    secure: N7+lKlNrQkJHEtEtl1CcwG9Q3GRLbH9kGD41NWfb0GbLsH9rHjMoIiCVkDF8jolr
version: 0.0.0.{build}
test_script:
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:GitHubKey):x-oauth-basic@github.com`n"
  - git config --global user.email "frederik@hjorslev.com"
  - git config --global user.name "Frederik Hjorslev Poulsen"
  - git config --global core.autocrlf false
  - git config --global core.safecrlf false
  - ps: Write-Host -Object "------------------ Invoke-Build ------------------"
  - ps: Invoke-Build
pull_requests:
  do_not_increment_build_number: true
build: off
